blank_issues_enabled: false

contact_links:
  - name: Discord Support
    url: https://go.happyareabean.cc/supportdiscord
    about: |
      Join our Discord for real-time support and community discussion.

  - name: Documentation
    url: https://docs.happyareabean.cc
    about: |
      Check out our docs for configuration guides and command reference.
